###
### Prerequisites
###

unless Vagrant.has_plugin?("vagrant-disksize")
    raise  Vagrant::Errors::VagrantError.new, "vagrant-disksize plugin is missing. Please install it using 'vagrant plugin install vagrant-disksize' and rerun 'vagrant up'"
end


###
### class ::Properties
###
class Properties

VAGRANT_CONFIGURE_VM_PROVIDER_VIRTUALBOX_GROUP_NAME = "tamama-machine"
VAGRANT_CONFIGURE_VM_PROVIDER_VIRTUALBOX_GROUP_PATH = "/" + VAGRANT_CONFIGURE_VM_PROVIDER_VIRTUALBOX_GROUP_NAME

end # ending class Properties


###
### Setup VM
###

Vagrant.configure("2") do |config|

  config.trigger.before :up do
    vagrant_root = File.dirname(__FILE__)
    Dir.mkdir "#{vagrant_root}/workspace"      unless File.exists?("#{vagrant_root}/workspace")
  end

  config.disksize.size = '100GB'

  config.vagrant.plugins = ['vagrant-vbguest']
  config.vbguest.auto_update = true

  config.vm.define :rhel9_test do |node|

      node.vm.box = "generic/rhel9"

      node.vm.hostname = "tamama-machine"

      #node.vm.network :forwarded_port , guest: 22 , host: 30022, protocol: "tcp", id: "ssh"
      #node.vm.network :forwarded_port , guest: 8888 , host: 38888, host_ip: "127.0.0.1", protocol: "tcp", id: "jupyter" 

      node.vm.provider :virtualbox do |vb|
      vb.name = ::Properties::VAGRANT_CONFIGURE_VM_PROVIDER_VIRTUALBOX_GROUP_NAME + ".rhel-9-test"
      vb.customize ["modifyvm", :id, "--groups", ::Properties::VAGRANT_CONFIGURE_VM_PROVIDER_VIRTUALBOX_GROUP_PATH]
      vb.customize ["modifyvm", :id, "--memory", "8192", "--cpus", "4"]
      end

      node.vm.synced_folder ".", "/mnt/tamama"

      node.vm.provision "shell", inline: <<-END_OF_SHELL
        
        ###
        ### Load user environmental settings
        ###

        mkdir -p /etc/envrc.d
        echo "Zm9yIGkgaW4gL2V0Yy9lbnZyYy5kLyouZW52cmMgOyBkbwogICAgaWYgWyAtciAiJGkiIF07IHRoZW4KICAgICAgICBpZiBbICIkey0jKml9IiAhPSAiJC0iIF07IHRoZW4gCiAgICAgICAgICAgIC4gIiRpIgogICAgICAgIGVsc2UKICAgICAgICAgICAgLiAiJGkiID4vZGV2L251bGwKICAgICAgICBmaQogICAgZmkKZG9uZQo=" \
            | base64 -di \
            > /etc/envrc
        cp -f /mnt/tamama/.envrc /etc/envrc.d/tamama-vagrant.envrc || true
        . /etc/envrc
        
        ###
        ### Register VM on Redhat
        ###

        subscription-manager register \
          --username $REDHAT_SUBSCRIPTION_MANAGER_USERNAME \
          --password $REDHAT_SUBSCRIPTION_MANAGER_PASSWORD \
          --auto-attach \
          --force 

        ###
        ### Install Terraform
        ###
        
        yum install -y yum-utils
        yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
        yum install -y terraform

      END_OF_SHELL

  end

end
